# Site settings
title: 1am Studios - Jeff Harris
email: jeff@1amstudios.com
description: > # this means to ignore newlines until "baseurl:"
  Random hacks, tools, products, explorations of retro tech! I am software engineer, sometime entrepreneur, New Zealander living in San Francisco
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://1amstudios.com" # the base hostname & protocol for your site
twitter_username: 1amstudios
github_username:  jeff-1amstudios
linkedin_username: jeffrey-harris-6763594
youtube_username: 1amStudios

# Build settings
markdown: kramdown
permalink:     pretty

paginate: 3
exclude:
    - deploy
plugins:
   - jekyll-paginate

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
